#!/bin/bash
#
# A minimal CLI for the Routing Challenge.

# Constants
readonly IMAGE_BASE_DIR="solutions"

#######################################
# Display an error message when the user input is invalid.
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   None
#######################################
err() {
  echo "$0: $1" >&2
}

# Single main function
main() {
  if [[ $# -lt 1 ]]; then
    err "missing docker-image operand"
    exit 1
  elif [[ $# -gt 1 ]]; then
    err "too many arguments"
    exit 1
  elif [[ ! -f "${IMAGE_BASE_DIR}/$1" ]]; then
    err "cannot find '$1': No such file or directory"
    exit 1
  fi

  # Run the app container within an instance of the trainer.
  docker run --privileged --rm --env IMAGE_NAME=$1 \
    --volume "$(pwd)"/${IMAGE_BASE_DIR}:/solutions:ro \
    --volume "$(pwd)"/data/inputs:/data/inputs:ro \
    --volume "$(pwd)"/data/outputs:/data/outputs \
    rctrain
}

main "$@"
